In [18]:
""""- check the quality of the data ( the output should be a report(how many missing entries? …..))
- improve the quality of the data/ look at the quality of the data (  look at duplicate and remove them, look at the useless column and remove them, look at error and fix them, look at missing entries and replace them) 
- analyze the data [statistics]
- ether split the data into training and testing data 
- build classification model ( pick 5( desertion tree, KNN, SVM)  different classifiers to run ) 
- build a model based on training set 
- build a model based on testing set 
- preform cross validation 
- show me the accuracy of the model ( show the 5 models accuracy in table/ and show the best model based on accuracy ) 
- show me the contribution matrix ( calculated for each model) 
- analysis  (with visualization “graph”) ( the relationships between true positives true negative false positive false negative  )
- show the performance of the models ( compare the performance in a graph) 
- evaluate the model 
-Clean the data 
- create a pickle file 



So the key words is : 
 ⁃ Quality 
 ⁃ Improve 
 ⁃ Analyze 
 ⁃ Split 
 ⁃ Classification model 
 ⁃ Training 
 ⁃ Testing 
 ⁃ cross validation
 ⁃ Accuracy 
 ⁃ contribution matrix
 ⁃ analysis
 ⁃ Performance
 ⁃ Evaluate 
 ⁃ Clean
 ⁃ Pickle"""

'"- check the quality of the data ( the output should be a report(how many missing entries? …..))\n- improve the quality of the data/ look at the quality of the data (  look at duplicate and remove them, look at the useless column and remove them, look at error and fix them, look at missing entries and replace them) \n- analyze the data [statistics]\n- ether split the data into training and testing data \n- build classification model ( pick 5( desertion tree, KNN, SVM)  different classifiers to run ) \n- build a model based on training set \n- build a model based on testing set \n- preform cross validation \n- show me the accuracy of the model ( show the 5 models accuracy in table/ and show the best model based on accuracy ) \n- show me the contribution matrix ( calculated for each model) \n- analysis  (with visualization “graph”) ( the relationships between true positives true negative false positive false negative  )\n- show the performance of the models ( compare the performance in 

In [65]:
import pandas as pd
import numpy as np
import re
import string
from nltk.stem import WordNetLemmatizer
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from nltk.tokenize import RegexpTokenizer
from nltk import PorterStemmer, WordNetLemmatizer
import pickle
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

In [66]:
df=pd.read_csv("Dataset.csv")


In [67]:
len(df)

32561

In [68]:
df.isna().sum().values.tolist()

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [69]:
df.sort_values("age", inplace=True)
df=df.drop_duplicates()
df=df.drop(['education', 'marital.status','native.country','occupation','relationship','race'], axis=1)
len(df)

32537

In [70]:
df

age workclass  fnlwgt  education.num     sex  capital.gain  \
4159    17   Private  130125              6  Female          1055   
18810   17   Private  187308              6  Female             0   
25709   17   Private  153021              8  Female             0   
6046    17         ?  103810              8    Male             0   
8682    17         ?  127003              5    Male             0   
...    ...       ...     ...            ...     ...           ...   
8914    90   Private   51744             14    Male             0   
8791    90   Private  141758              5  Female             0   
7756    90   Private  313986              7    Male             0   
14659   90   Private   40388             13    Male             0   
0       90         ?   77053              9  Female             0   

       capital.loss  hours.per.week  income  
4159              0              20       0  
18810             0              15       0  
25709             0              20       0  
6046              0              40       0  
8682              0              40       0  
...             ...             ...     ...  
8914              0              50       1  
8791              0              40       0  
7756              0              40       0  
14659             0              55       0  
0              4356              40       0  

[32537 rows x 9 columns]

In [71]:
df.describe()

age        fnlwgt  education.num  capital.gain  capital.loss  \
count  32537.000000  3.253700e+04   32537.000000  32537.000000  32537.000000   
mean      38.585549  1.897808e+05      10.081815   1078.443741     87.368227   
std       13.637984  1.055565e+05       2.571633   7387.957424    403.101833   
min       17.000000  1.228500e+04       1.000000      0.000000      0.000000   
25%       28.000000  1.178270e+05       9.000000      0.000000      0.000000   
50%       37.000000  1.783560e+05      10.000000      0.000000      0.000000   
75%       48.000000  2.369930e+05      12.000000      0.000000      0.000000   
max       90.000000  1.484705e+06      16.000000  99999.000000   4356.000000   

       hours.per.week        income  
count    32537.000000  32537.000000  
mean        40.440329      0.240926  
std         12.346889      0.427652  
min          1.000000      0.000000  
25%         40.000000      0.000000  
50%         40.000000      0.000000  
75%         45.000000      0.000000  
max         99.000000      1.000000

In [72]:
df['income'].argmax()

1159

In [73]:
df['income'].value_counts()

0    24698
1     7839
Name: income, dtype: int64

In [74]:
df.iloc[[df['income'].argmax()]]

age workclass  fnlwgt  education.num   sex  capital.gain  capital.loss  \
10961   19   Private  323605              4  Male             0             0   

       hours.per.week  income  
10961              60       1

In [75]:
labelencoder = LabelEncoder()
df['workclass'] = labelencoder.fit_transform(df['workclass'])
df['sex'] = labelencoder.fit_transform(df['sex'])

In [76]:
df.head()

age  workclass  fnlwgt  education.num  sex  capital.gain  capital.loss  \
4159    17          4  130125              6    0          1055             0   
18810   17          4  187308              6    0             0             0   
25709   17          4  153021              8    0             0             0   
6046    17          0  103810              8    1             0             0   
8682    17          0  127003              5    1             0             0   

       hours.per.week  income  
4159               20       0  
18810              15       0  
25709              20       0  
6046               40       0  
8682               40       0

# split the data

In [77]:
x=df.iloc[:,:8]
y=df.iloc[:,8:]
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size= 0.25, random_state= 0)

In [78]:
#Feature Scaling
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_test

array([[ 0.62265628,  0.08794759,  3.72443053, ..., -0.14550991,
        -0.21536826, -0.03769198],
       [ 0.91661914,  1.46057119, -0.69979643, ..., -0.14550991,
        -0.21536826, -0.03769198],
       [ 0.99010986,  0.08794759, -0.09265472, ..., -0.14550991,
        -0.21536826,  1.58188845],
       ...,
       [-1.58206519,  0.08794759, -1.05200122, ..., -0.14550991,
        -0.21536826, -1.65727241],
       [ 1.79850773, -1.97098781, -1.42474317, ..., -0.14550991,
         6.17722508,  1.58188845],
       [ 0.10822127,  0.08794759,  5.76231851, ..., -0.14550991,
        -0.21536826, -0.19965002]])

In [79]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
def models(X_train,Y_train):
  lr=LinearRegression()
  lr.fit(X_train,Y_train)
  svm = SVC(kernel= 'linear', C = 1).fit(X_train, y_train)
  #Using RandomForestClassifier()
  rf=RandomForestClassifier()
  rf.fit(X_train,Y_train)
   #Using KNeighborsClassifier 
  knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
  knn.fit(X_train, Y_train)

  #Using DecisionTreeClassifier 
  tree = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
  tree.fit(X_train, Y_train)
    
  
  #print model accuracy on the training data.
  print('[1]K Nearest Neighbor Training Accuracy:', knn.score(X_train, Y_train))
  print('[2]Decision Tree Classifier Training Accuracy:', tree.score(X_train, Y_train))
  print('[3]Random Forest Classifier Training Accuracy:', rf.score(X_train, Y_train))
  print('[4]SVM Classifier Training Accuracy:', svm.score(X_train, Y_train))
  print('[5]LinearRegression Classifier Training Accuracy:', lr.score(X_train, Y_train))
  
  
  
  return  lr,svm,rf,knn,tree

In [85]:
lr,svm,rf,knn,tree = models(X_train,y_train)

C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\dell\AppData\Local\Temp\ipykernel_10424\3330594993.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train,Y_train)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it ac

[1]K Nearest Neighbor Training Accuracy: 0.8657487091222031
[2]Decision Tree Classifier Training Accuracy: 0.9993443160396689
[3]Random Forest Classifier Training Accuracy: 0.9993033357921481
[4]SVM Classifier Training Accuracy: 0.8114089009097615
[5]LinearRegression Classifier Training Accuracy: 0.25050029457188294


In [87]:
model=[lr,svm,rf,knn,tree]

In [90]:
#Show the confusion matrix and the accuracy of the models on the test data.
for i in model:
  try:
      cm = confusion_matrix(y_test, i.predict(X_test))

      TN = cm[0][0]
      TP = cm[1][1]
      FN = cm[1][0]
      FP = cm[0][1]

      print(cm)
      print('Model[{}] Testing Accuracy = "{}!"'.format(i,  (TP + TN) / (TP + TN + FN + FP)))
  except:
    pass
  print()# Print a new line


[[6012  148]
 [1385  590]]
Model[SVC(C=1, kernel='linear')] Testing Accuracy = "0.8115550092194223!"

[[5680  480]
 [ 891 1084]]
Model[RandomForestClassifier()] Testing Accuracy = "0.8314689612784265!"



C:\Users\dell\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


[[5656  504]
 [1006  969]]
Model[KNeighborsClassifier()] Testing Accuracy = "0.8143822987092809!"

[[5217  943]
 [ 839 1136]]
Model[DecisionTreeClassifier(criterion='entropy', random_state=0)] Testing Accuracy = "0.7809465273509527!"



In [93]:
#Show other ways to get the classification accuracy & other metrics 
for i in range(len(model)):
  try:
      print('Model ',i)
      #Check precision, recall, f1-score
      print( classification_report(y_test, model[i].predict(X_test)) )
      #Another way to get the models accuracy on the test data
      print( accuracy_score(y_test, model[i].predict(X_test)))
      print()#Print a new line
  except:
    pass

Model  0
Model  1
              precision    recall  f1-score   support

           0       0.81      0.98      0.89      6160
           1       0.80      0.30      0.43      1975

    accuracy                           0.81      8135
   macro avg       0.81      0.64      0.66      8135
weighted avg       0.81      0.81      0.78      8135

0.8115550092194223

Model  2
              precision    recall  f1-score   support

           0       0.86      0.92      0.89      6160
           1       0.69      0.55      0.61      1975

    accuracy                           0.83      8135
   macro avg       0.78      0.74      0.75      8135
weighted avg       0.82      0.83      0.82      8135

0.8314689612784265

Model  3


C:\Users\dell\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


              precision    recall  f1-score   support

           0       0.85      0.92      0.88      6160
           1       0.66      0.49      0.56      1975

    accuracy                           0.81      8135
   macro avg       0.75      0.70      0.72      8135
weighted avg       0.80      0.81      0.80      8135



C:\Users\dell\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


0.8143822987092809

Model  4
              precision    recall  f1-score   support

           0       0.86      0.85      0.85      6160
           1       0.55      0.58      0.56      1975

    accuracy                           0.78      8135
   macro avg       0.70      0.71      0.71      8135
weighted avg       0.78      0.78      0.78      8135

0.7809465273509527



In [95]:
#Print Prediction of KNN model
pred_k = model[-1].predict(X_test)
print(pred_k)

#Print a space
print()

#Print the actual values
print(y_test)

[1 0 0 ... 0 1 0]

       income
29826       1
13988       0
15476       0
31132       0
12118       0
...       ...
12995       0
6578        1
30155       0
35          1
30435       0

[8135 rows x 1 columns]


In [106]:
import pyttsx3
import speech_recognition as sr 
def speech_text():
        r = sr.Recognizer()
        with sr.Microphone() as source:

            audio_data = r.record(source, duration=5)
            print("Recognizing...")
            n = r.recognize_google(audio_data)
            #print(n)
            return n
speech_text()

Recognizing...
result2:
{   'alternative': [   {'confidence': 0.88687539, 'transcript': 'improve'},
                       {'transcript': 'impr'}],
    'final': True}


'improve'

In [102]:
!pip install   PyAudio

     -------------------------------------- 164.1/164.1 kB 1.4 MB/s eta 0:00:00
